image: alpine

stages:
  - compress
  - deploy

# Cache policy
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    # Actual build
    - ./*.tar.gz

# Linux docker container runner
.linux-docker-runner-template: &linux-docker-runner
  tags:
    - linux
    - docker


compress:
  <<: *linux-docker-runner
  stage: compress
  script:
    # Compose archive folder
    - mkdir .build
    - chmod -R 755 .build/
    - cp -r app/* .build/
    - cp README.md .build/
    # Compress folder
    - tar -czvf CafetApp-server-${CI_COMMIT_REF_SLUG}.tar.gz .build/*
    # Remove archive folder
    - rm -r .build


# Artifact publish templates
.publish-artifact-template: &publish-artifact
    name: application
    paths:
      - ./*.tar.gz
      - app/
.publish-template: &publish
  <<: *linux-docker-runner
  stage: deploy
  script: date
  dependencies:
    - compress

# Artifact publish
non tag application:
  <<: *publish
  except:
    - tags
  artifacts:
    <<: *publish-artifact
    expire_in: 1 day

application:
  <<: *publish
  only:
    - tags
  artifacts: *publish-artifact


# db structure templates
.db-struct-artifact-template: &db-struct-artifact
    name: database structure
    paths:
      - ./*.sql
.db-struct-template: &db-struct
  <<: *linux-docker-runner
  stage: deploy
  script:
    - cp docker/mysql/structure.sql .
    - cp docker/mysql/demo.sql .

# Artifact publish
non tag database structure:
  <<: *db-struct
  except:
    - tags
  artifacts:
    <<: *db-struct-artifact
    expire_in: 1 day

database structure:
  <<: *db-struct
  only:
    - tags
  artifacts: *db-struct-artifact