image: alpine

stages:
  - compress
  - deploy

# Linux docker container runner
.linux-docker-runner-template: &linux-docker-runner
  tags:
    - linux
    - docker


compress:
  <<: *linux-docker-runner
  stage: compress
  script:
    # Compose archive folder
    - mkdir . build
    - chmod -R 755 .build/
    - cp -r app/* .build/
    - cp README.md .build/
    # Compress folder
    - tar -czvf CafetApp-server-${CI_COMMIT_REF_SLUG}.tar.gz .build/
    # Remove archive folder
    - rm -rd .build


# Artifact publish templates
.publish-artifact-template: &publish-artifact
    name: application
    paths:
      - ./*.tar.gz
.publish-template: &publish
  <<: *linux-docker-runner
  stage: deploy
  script: date
  dependencies:
    - compress

# Artifact publish
publish:
  <<: *publish
  except:
    - tags
  artifacts:
    <<: *publish-artifact
    expire_in: 1 day

tag publish:
  <<: *publish
  only:
    - tags
  artifacts: *publish-artifact