stages:
  - build
  - test
  - deploy

variables:
  SERVER_IMAGE: $CI_REGISTRY_IMAGE/server
  DATABASE_IMAGE: $CI_REGISTRY_IMAGE/database
  IMAGE_TAG: ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}


default:
  image: alpine
  before_script:
    - date

# Jobs that does not require git to pull code
.no-pull: &no-pull
  variables:
      GIT_STRATEGY: none

.with-cache: &with-cache
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      # Node JS
      - ./node_modules

# Linux docker container runner
.linux-docker-runner-template: &linux-docker-runner
  tags:
    - linux
    - docker

# Jobs that require login
.docker_job: &docker
  <<: *linux-docker-runner
  image: docker:19
  services:
    - docker:dind
  before_script:
    - date
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY


## ##
## Build
## ##

build:docker:
  <<: *docker
  stage: build
  script:
    # fetches the latest image (not failing if image is not found)
    - docker pull $SERVER_IMAGE:latest || true
    - docker build --pull --cache-from $SERVER_IMAGE:latest -t $SERVER_IMAGE:$IMAGE_TAG -f docker/php/Dockerfile .
    - docker build --pull --cache-from $DATABASE_IMAGE:latest -t $DATABASE_IMAGE:$IMAGE_TAG -f docker/mysql/Dockerfile .
    - docker push $SERVER_IMAGE:$IMAGE_TAG
    - docker push $DATABASE_IMAGE:$IMAGE_TAG

build:documentation:
  <<: *linux-docker-runner
  <<: *with-cache
  image: node
  stage: build
  script:
    - npm install
    - npm run api:doc
    - cp openapi.yml doc/
  artifacts:
    untracked: true
    paths:
      # Built documentation
      - ./doc
    expire_in: 5 min

## ##
## Deploy
## ##

## Docker tags
.docker_tagging: &docker-tagging
    after_script:
        - docker pull $SERVER_IMAGE:$IMAGE_TAG
        - docker pull $DATABASE_IMAGE:$IMAGE_TAG
        - docker tag $SERVER_IMAGE:$IMAGE_TAG $SERVER_IMAGE:$VERSION
        - docker tag $DATABASE_IMAGE:$IMAGE_TAG $DATABASE_IMAGE:$VERSION
        - docker push $SERVER_IMAGE:$VERSION
        - docker push $DATABASE_IMAGE:$VERSION


deploy:branches:
  <<: *docker
  <<: *no-pull
  <<: *docker-tagging
  stage: deploy
  script:
    - VERSION=$CI_COMMIT_REF_NAME
  only:
    - branches
    - tags
  except:
    refs:
      - master
      - develop
    variables:
      - $CI_COMMIT_TAG =~ /^v/
  dependencies:
    - build:docker    

deploy:tags:
  <<: *docker
  <<: *no-pull
  <<: *docker-tagging
  stage: deploy
  script:
    - VERSION=$(echo $CI_COMMIT_TAG | sed -E "s/^v//")
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v/
  dependencies:
    - build:docker

deploy:release:
  <<: *docker
  <<: *no-pull
  <<: *docker-tagging
  stage: deploy
  script:
    - VERSION=latest
  only:
    - master
  except:
    - tags
  dependencies:
    - build:docker

deploy:develop:
  <<: *docker
  <<: *no-pull
  <<: *docker-tagging
  stage: deploy
  script:
    - VERSION=dev
  only:
    - develop
  except:
    - tags
  dependencies:
    - build:docker

## Artifacts

# Artifact publish templates
.publish-artifact-template: &publish-artifact
  name: application
  paths:
    - app/
.publish-template: &publish
  <<: *linux-docker-runner
  stage: deploy
  script: date

# Artifact publish
deploy:dev_app:
  <<: *publish
  except:
    - tags
  artifacts:
    <<: *publish-artifact
    expire_in: 1 day

deploy:app:
  <<: *publish
  only:
    - tags
  artifacts: *publish-artifact


# db structure templates
.db-struct-artifact-template: &db-struct-artifact
  name: database structure
  paths:
    - ./*.sql
.db-struct-template: &db-struct
  <<: *linux-docker-runner
  stage: deploy
  script:
    - cp docker/mysql/structure.sql .
    - cp docker/mysql/demo.sql .

# Artifact publish
deploy:dev_database_structure:
  <<: *db-struct
  except:
    - tags
  artifacts:
    <<: *db-struct-artifact
    expire_in: 1 day

deploy:database_structure:
  <<: *db-struct
  only:
    - tags
  artifacts: *db-struct-artifact


pages:
  <<: *linux-docker-runner
  stage: deploy
  dependencies:
    - build:documentation
  script: 
    - pwd
    - ls -l
    - mv doc public
  artifacts:
    paths:
      - public
    expire_in: 5 mins
