stages:
  - build
  - docker
  - test
  - deploy

variables:
  SERVER_IMAGE: "$CI_REGISTRY_IMAGE/server"
  DATABASE_IMAGE: "$CI_REGISTRY_IMAGE/database"
  IMAGE_ID: ${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}


default:
  image: alpine
  before_script:
    - date

include:
  - /.gitlab/ci/app.gitlab-ci.yml
  - /.gitlab/ci/deploy.gitlab-ci.yml
  - /.gitlab/ci/docker.gitlab-ci.yml
  - /.gitlab/ci/docs.gitlab-ci.yml
  - /.gitlab/ci/setup.gitlab-ci.yml
