version: "3"
services:
  php:
    image: registry.gitlab.com/cafet-app/cafet-app/server:latest
    container_name: cafet-server
    environment:
      SERVER_DOMAIN: localhost
      MAILHUB: localhost
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db
    volumes:
      - php-logs:/var/log

  db:
    image: registry.gitlab.com/cafet-app/cafet-app/database:latest
    container_name: cafet-server-mysql
    restart: always
    ports:
      - '3306:3306'

volumes:
  php-logs: