## ##
## Build
## ##

build:js:
  extends: .node
  stage: build
#  before_script:
#    - apt-get update -q
#    - apt-get install -y --no-install-recommends python2.7 build-essential
#    - apt-get clean
#    - rm -rfd /var/lib/apt/lists/*
  script:
    - yarn install
    - yarn prod:build
  artifacts:
    paths:
      - ./server/dist
    expire_in: 1 hour

## ##
## Deploy
## ##

# Artifact publish templates
.publish-artifact-template: &publish-artifact
  name: application
  paths:
    - app/
    - sql_scripts/
.app: &app
  extends: .default-runner
  stage: deploy
  dependencies:
    - build:js
  script:
    - date
    - cp -r server app
    - mkdir sql_scripts
    - cp docker/mysql/structure.sql sql_scripts
    - cp docker/mysql/demo.sql sql_scripts

# Artifact publish
deploy:dev_app:
  extends:
    - .app
    - .only-nonstable
  artifacts:
    <<: *publish-artifact
    expire_in: 1 day

deploy:app_versions:
  extends:
    - .app
    - .only-stable
  artifacts: *publish-artifact
