## ##
## Build
## ##

build:js:
  extends: .node
  stage: build
  before_script:
    - cd web-client
  script:
    - yarn install
    - yarn prod:build
  artifacts:
    paths:
      - ./server/dist
    expire_in: 1 hour

## ##
## Deploy
## ##

.app:
  extends: .default-runner
  stage: deploy
  dependencies:
    - build:js
  script:
    - date
    - cp -r server app
    - mkdir sql_scripts
    - cp docker/mysql/structure.sql sql_scripts
    - cp docker/mysql/demo.sql sql_scripts
  artifacts:
    name: application
    paths:
      - app/
      - sql_scripts/

# Artifact publish
deploy:dev_app:
  extends:
    - .app
    - .only-nonstable
    - .artifact-one-day

deploy:app:
  extends:
    - .app
    - .only-stable
