build:documentation:
  extends:
    - .node
    - .only-master
  stage: build
  script:
    - npx redoc-cli bundle openapi.yml -o doc/index.html
    - cp openapi.yml doc/
  artifacts:
    untracked: true
    paths:
      # Built documentation
      - ./doc
    expire_in: 1 hour

# pages
pages:
  extends: .only-master
  stage: deploy
  dependencies:
    - build:documentation
  script:
    - mv doc public
  artifacts:
    paths:
      - public
    expire_in: 5 mins
