build:documentation:
  extends:
    - .linux-docker-runner
    - .with-cache
    - .only-master
  image: node:10-stretch-slim
  stage: build
  script:
    - yarn install
    - yarn api:doc
    - cp openapi.yml doc/
  artifacts:
    untracked: true
    paths:
      # Built documentation
      - ./doc
    expire_in: 1 hour

# pages
pages:
  extends:
    - .linux-docker-runner
    - .only-master
  stage: deploy
  dependencies:
    - build:documentation
  script:
    - mv doc public
  artifacts:
    paths:
      - public
    expire_in: 5 mins
