.default-runner: &default-runner
  # Linux docker container runner
  tags:
    - linux
    - docker

.with-cache: &with-cache
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      # Node JS
      - ./node_modules

# Job running with node (12.13)
.node: &node
  extends:
    - .default-runner
    - .with-cache
  image: node:12.13-stretch # no slim or alpine as we want to have different build tools

# Jobs that require login
.docker: &docker
  extends: .default-runner
  image: docker:19
  services:
    - docker:dind
  before_script:
    - date
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

# Only policies
.only-master: &only-master
  only:
    - master
  except:
    - tags

.only-dev: &only-dev
  only:
    - develop
  except:
    - tags

.only-versions: &only-versions
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v/

.only-stable: &only-stable
  only:
    refs:
      - tags
      - branches
    variables:
      - $CI_COMMIT_TAG =~ /^v/
      - $CI_COMMIT_REF_NAME == "master"


.only-nonstable: &only-nonstable
  only:
    - branches
    - tags
  except:
    refs:
      - master
    variables:
      - $CI_COMMIT_TAG =~ /^v/

.only-others: &only_others
  only:
    - branches
    - tags
  except:
    refs:
      - master
      - develop
    variables:
      - $CI_COMMIT_TAG =~ /^v/
